sudo: false
os:
    - linux
    - osx
cache:
    directories:
        - $HOME/.stack
addons:
  apt:
    packages:
        - libgmp-dev
env:
    - STACK_ARGS="--resolver lts-5"
    - STACK_ARGS="--resolver lts-3"
    - STACK_ARGS="--resolver lts-2"

before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then mkdir -p ~/.local/bin ; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH=$HOME/.local/bin:$PATH ; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack' ; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update ; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install haskell-stack ; fi

install:
    - stack $STACK_ARGS --no-terminal setup
    - stack $STACK_ARGS --no-terminal test --only-snapshot

script:
    - stack $STACK_ARGS --no-terminal build bond-haskell-compiler
    - stack $STACK_ARGS --no-terminal test bond-haskell
