sudo: false
os:
    - linux
    - osx
cache:
    directories:
        - $HOME/.stack
        - $HOME/.cabal
addons:
  apt:
    sources:
        - hvr-ghc
    packages:
        - libgmp-dev
        - ghc-7.8.4
        - ghc-7.10.3
env:
    - STACK_ARGS="--resolver lts-6"
    - STACK_ARGS="--resolver lts-5"
    - STACK_ARGS="--resolver lts-2"

before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then mkdir -p ~/.local/bin ; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH=$HOME/.local/bin:$PATH ; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack' ; fi
    - if [ "$STACK_ARGS" == "--resolver lts-6" ]; then export PATH=/opt/ghc/7.10.3/bin:$PATH ; fi
    - if [ "$STACK_ARGS" == "--resolver lts-5" ]; then export PATH=/opt/ghc/7.10.3/bin:$PATH ; fi
    - if [ "$STACK_ARGS" == "--resolver lts-2" ]; then export PATH=/opt/ghc/7.8.4/bin:$PATH ; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update ; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install haskell-stack ; fi

install:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then stack $STACK_ARGS --no-terminal setup ; fi
    - stack $STACK_ARGS --no-terminal test --only-snapshot

script:
    - stack $STACK_ARGS --no-terminal build bond-haskell-compiler
    - stack $STACK_ARGS --no-terminal test bond-haskell
